In [7]:
import pandas as pd
import json
import urllib
from urllib.request import urlopen
import re

In [8]:
def refactor_values(data):
    new_data = {}
    for key, value in data.items():
            if value != '':
                new_data[key] = value
            if isinstance(value, str) and '<' in value:
                new_value = value.split('<')[1]
                new_data[key] = int(new_value)
    return new_data

In [15]:
url = "https://arsoxmlwrapper.app.grega.xyz/api/air/archive"

response = urlopen(url)
data_json = json.loads(response.read())

json_object = json.dumps(data_json)

In [18]:
save_file = open("data/raw/raw", "w")  
json.dump(data_json, save_file)  
save_file.close()

In [19]:
load_file = open('data/raw/raw')
dataJson = json.load(load_file)
load_file.close()

In [20]:
df = pd.DataFrame()

for i in range(len(dataJson)):
    data = dataJson[i]
    dictData = json.loads(data['json'])
    
    df1 = pd.json_normalize(dictData['arsopodatki']['postaja'])
    df = pd.concat([df, df1])#, axis=1, join="inner")

In [21]:
df = df.reset_index(drop=True)

In [ ]:
####

In [6]:
#file = open('../data/raw/data.json', 'r', encoding='utf-8')
#raw = json.load(file)
#file.close()



#df = pd.DataFrame()

#for i in range(len(raw)):
#    jdata = json.loads(raw[i]['json'])
#    station = jdata['arsopodatki']['postaja']
#    for i in range(len(station)):
#        data = station[i]
#        data = refactor_values(data)
#        df = pd.concat([df, pd.json_normalize(data)])  
        
#df

KeyboardInterrupt:

In [ ]:
####

In [22]:
print(df.isnull().sum())

pm2.5             14370
nadm_visina           0
datum_od              0
merilno_mesto         0
o3                71850
benzen           129330
ge_sirina          7185
pm10              14370
co               143700
no2               71850
sifra                 0
datum_do              0
ge_dolzina         7185
so2              129330
dtype: int64

In [23]:
cat_cols = df.select_dtypes(include=['object']).columns
print(cat_cols)
num_cols = df.select_dtypes(include=['number']).columns
print(num_cols)

Index(['pm2.5', 'datum_od', 'merilno_mesto', 'o3', 'benzen', 'pm10', 'co',
       'no2', 'sifra', 'datum_do', 'so2'],
      dtype='object')
Index(['nadm_visina', 'ge_sirina', 'ge_dolzina'], dtype='object')

In [24]:
for col in num_cols:
    df[col].fillna((df[col].mean()), inplace=True)

df_location = pd.get_dummies(df['merilno_mesto'])
df = pd.concat([df, df_location], axis=1).reindex(df.index)
df.pop('merilno_mesto')
df.pop('sifra')
df.pop('datum_od')
df.pop('datum_do')

df

,pm2.5,nadm_visina,o3,benzen,ge_sirina,pm10,co,no2,ge_dolzina,so2,...,MB Vrbanski,MS Cankarjeva,MS Rakičan,NG Grčna,Novo mesto,Otlica,Ptuj,Rečica v I.Bistrici,Trbovlje,Zagorje
0,34.0,299,61,,46.065851,39.0,0.3,19,14.517454,NaN,...,0,0,0,0,0,0,0,0,0,0
1,38.0,305,NaN,NaN,46.072399,46.0,NaN,38,14.491849,NaN,...,0,0,0,0,0,0,0,0,0,0
2,35.0,293,NaN,NaN,46.037791,40.0,NaN,NaN,14.494001,NaN,...,0,0,0,0,0,0,0,0,0,0
3,88.0,388,NaN,NaN,46.242115,95.0,NaN,NaN,14.366963,NaN,...,0,0,0,0,0,0,0,0,0,0
4,33.0,270,NaN,2.3,46.559202,41.0,NaN,32,15.656191,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150880,26,241,17,NaN,46.131416,30,NaN,30,15.000906,4.0,...,0,0,0,0,0,0,0,0,0,1
150881,14,290,NaN,NaN,46.144213,15,NaN,NaN,15.088097,NaN,...,0,0,0,0,0,0,0,0,0,0
150882,41,220,9,NaN,45.802080,44,NaN,19,15.182060,NaN,...,0,0,0,0,1,0,0,0,0,0
150883,10,540,36,,45.561344,13,NaN,4,14.862816,2.0,...,0,0,0,0,0,0,0,0,0,0
150884,NaN,1742,71,NaN,46.297680,NaN,NaN,NaN,14.538062,NaN,...,0,0,0,0,0,0,0,0,0,0

In [25]:
df.to_csv('../data/processed/data.csv', index=False)